services:
  - type: web
    name: nsa-diu
    env: php
    buildCommand: "./render-build.sh"
    startCommand: "heroku-php-apache2 public/"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: array
      - key: QUEUE_CONNECTION
        value: sync
    plan: free

databases:
  - name: nsa-diu-db
    databaseName: nsadiu
    user: nsadiu
    plan: free
